name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php:
          - "8.0"
          - "8.1"
        dependencies:
          - "lowest"
          - "highest"
        symfony-yaml: ['^5', '^6']
        include:
          - os: "windows-latest"
            php: "8.1"
            dependencies: "highest"
            symfony-yaml: '5.4.3'
          - os: "macos-latest"
            php: "8.1"
            dependencies: "highest"
            symfony-yaml: '^5'
        exclude:
          - php: '8.1'
            symfony-yaml: '^5'
            dependencies: "lowest"
          - php: '8.1'
            symfony-yaml: '^6'
            dependencies: "lowest"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          tools: composer:v2

      - name: Require specific symfony/yaml version
        run: "composer require symfony/yaml:'${{ matrix.symfony-yaml }}' --prefer-dist --no-interaction --ansi --no-install"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: Validate test data
        run: make lint

      - name: PHPUnit tests
        run: make test

      - name: Code coverage
        run: make coverage
